openapi: 3.0.1
info:
  title: urban-geo-locator
  description: Urban Test Task Server
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: GeoLocation
  description: Endpoint to find service are, address and coordinates by user-entered address
- name: Specification
  description: The swagger API specification
paths:
  /geolocation:  
    get:
      tags:
      - GeoLocation
      description: Finds service are—Ñ, address and coordinates by user-entered address
      parameters:
      - name: search
        in: query
        description: search ID
        required: true
        schema:
          type: string
      - name: address
        in: query
        description: user-entered address
        required: true
        schema:
          type: string
      responses:
        200:
          description: Returns service area, address and coordinates by user-entered address
          content: {}
        500:
          description: Error occurred
          content: {}
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
